language: php
sudo: required
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        - $HOME/.php-cs-fixer

services:
  - docker

env:
    global:
        - TEST_COMMAND="composer test"
        - COMPOSER_FLAGS="--prefer-dist"
        - SYMFONY_PHPUNIT_VERSION=6.5

matrix:
    fast_finish: true
    include:
        # Test with lowest dependencies
      - php: 7.1
        env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

        # Test the latest stable release
      - php: 7.1
        env: COVERAGE=true TEST_COMMAND="composer test-ci"
      - php: 7.2
        env: CS=true

        # Force some major versions of Symfony
      - php: 7.1
        env: DEPENDENCIES="dunglas/symfony-lock:^3"
      - php: 7.1
        env: DEPENDENCIES="dunglas/symfony-lock:^4"

before_install:
  - sed -i -e "s/FROM php:7.2/FROM php:${TRAVIS_PHP_VERSION:0:3}/g" ./Dockerfile
  - docker build -t buzz .

script:
  - docker run -e TEST_COMMAND -e COMPOSER_FLAGS -e SYMFONY_PHPUNIT_VERSION -e DEPENDENCIES -e COVERAGE -e CS -e TRAVIS buzz /bin/sh -c '/home/docker/run.sh'